version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: flutter-foundation:master    # Required. Must be in the same fork network.
    mergeMethod: merge      # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
    conflictReviewers:
      - matthew-carroll
  - base: beta
    upstream: flutter-foundation:beta      # Required. Can be a branch in the same forked repo.
    mergeMethod: merge      # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - matthew-carroll
  - base: stable
    upstream: flutter-foundation:stable    # Required. Can be a branch in the same forked repo.
    mergeMethod: merge      # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - matthew-carroll

conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict